version: "3.5"

services:
  adminer:
    image: adminer
    container_name: ${CONTAINER_PREFIX}adminer
    restart: unless-stopped
    environment:
      - "ADMINER_DEFAULT_SERVER=${MYSQL_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.entrypoints=https"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - mysql
      - traefik
    env_file:
      - adminer.env
networks:
  mysql:
    external:
      name: mysql
  traefik:
    external:
      name: traefik
