  
version: '3.5'

services: 
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: dingfudata
    domainname: ldap.dingfudata.com
    depends_on:
      - db
      - ldap
    links:
      - db
      - ldap:ldap.dingfudata.com
    ports: 
      - 6443:443  
    restart: always
    environment:
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: dingfu
      LDAP_DB_NAME: ldap
      PHPLDAPADMIN_LDAP_HOSTS: ldap.dingfudata.com   
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"

  openldap:
    image: osixia/openldap:1.3.0    
    domainname: ${BASE_URL}
    hostname: openldap
    # ports:
    #   - "389:389"
    volumes:
      - "./.data/var/lib/ldap:/var/lib/ldap"
      - "./.data/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    restart: always    
    environment: 
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: dingfu
      LDAP_DB_NAME: ldap 
      LDAP_ORGANISATION: DingFu
      LDAP_DOMAIN: ldap.dingfudata.com
      LDAP_ADMIN_PASSWORD: XXXXXXXX
      LDAP_TLS: "false"

networks:
  default:
    external:
      name: traefik
