version: "3.5"

services:
  collabora:
    build: ./${MODULE_NAME}
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    restart: unless-stopped
    cap_add:
      - MKNOD
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=https"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_DOMAIN}`)"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
    networks:
      - traefik
    env_file:
      - .env
networks:
  traefik:
    external: true
    name: traefik
