version: "3.5"

services:
  meshcentral:
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    build: ./${MODULE_NAME}
    restart: unless-stopped
    dns:
      - ${LOCAL_DNS_SERVER}
    ports:
      # the port of Intel" AMT CIRA (Client Initiated Remote Access) connections, MpsPort
      - ${MESHCENTRAL_MPS_PORT}:${MESHCENTRAL_MPS_PORT}
    env_file:
      - .env
    volumes:
      - "${DATA_PATH}/meshcentral/meshcentral-data:/opt/meshcentral/meshcentral-data"
      - "${DATA_PATH}/meshcentral/meshcentral-files:/opt/meshcentral/meshcentral-files"
      - "${DATA_PATH}/meshcentral/meshcentral-web:/opt/meshcentral/meshcentral-web"
      - "${DATA_PATH}/meshcentral/meshcentral-backups:/opt/meshcentral/meshcentral-backups"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meshcentral.entrypoints=https"
      - "traefik.http.routers.meshcentral.rule=Host(`${MESHCENTRAL_DOMAIN}`)"
      - "traefik.http.routers.meshcentral.tls=true"
      - "traefik.http.services.meshcentral.loadbalancer.server.port=${TRAEFIK_BASE_PORT}"
    networks:
      - mysql
      - traefik
networks:
  default:
    driver: bridge
    name: meshcentral
  mysql:
    name: mysql
    external: true
  traefik:
    name: traefik
    external: true