version: "3.5"

services:
  nextcloud:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud
    volumes:
      - "${NEXTCLOUD_PATH}:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-webfinger,nextcloud-regex,nextcloud-header"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-webfinger.replacepathregex.regex=^(/.well-known.*)"
      - "traefik.http.middlewares.nextcloud-webfinger.replacepathregex.replacement=/index.php$${1}"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nextcloud-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nextcloud-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
    env_file:
      - nextcloud.env
      - .env
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_DB_NAME}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "REAL_IP_FROM=${NEXTCLOUD_CONTAINER_NAME}"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  cron:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_cron
    depends_on:
      - nextcloud
    volumes:
      - "${NEXTCLOUD_PATH}:/data"
    env_file:
      - nextcloud.env
      - .env
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_DB_NAME}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/5 * * * *"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  previewgen:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_previewgen
    depends_on:
      - nextcloud
    volumes:
      - "${NEXTCLOUD_PATH}:/data"
    env_file:
      - nextcloud.env
      - .env
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_DB_NAME}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_PREVIEWGEN=1"
      - "PREVIEWGEN_PERIOD=0 * * * *"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  news_updater:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_news_updater
    depends_on:
      - nextcloud
    volumes:
      - "${NEXTCLOUD_PATH}:/data"
    env_file:
      - nextcloud.env
      - .env
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_DB_NAME}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_NEWSUPDATER=1"
      - "NC_NEWSUPDATER_THREADS=10"
      - "NC_NEWSUPDATER_TIMEOUT=300"
      - "NC_NEWSUPDATER_INTERVAL=900"
      - "NC_NEWSUPDATER_LOGLEVEL=error"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

networks:
  default:
    driver: bridge
    name: nextcloud
  mysql:
    external:
      name: mysql
  traefik:
    external:
      name: traefik
