version: "3.5"

services:
  nextcloud:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud
    volumes:
      - "${DATA_PATH}/nextcloud:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-regex"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.permanent=true"
    env_file:
      - "./nextcloud.env"
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_MYSQL_DATABASE}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  cron:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_cron
    depends_on:
      - nextcloud
    volumes:
      - "${DATA_PATH}/nextcloud:/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_MYSQL_DATABASE}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/5 * * * *"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  previewgen:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_previewgen
    depends_on:
      - nextcloud
    volumes:
      - "${DATA_PATH}/nextcloud:/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_MYSQL_DATABASE}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_PREVIEWGEN=1"
      - "PREVIEWGEN_PERIOD=0 * * * *"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

  news_updater:
    build: ./nextcloud
    image: ${IMAGE_PREFIX}nextcloud:latest
    container_name: ${CONTAINER_PREFIX}nextcloud_news_updater
    depends_on:
      - nextcloud
    volumes:
      - "${DATA_PATH}/nextcloud:/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${NEXTCLOUD_MYSQL_DATABASE}"
      - "DB_USER=root"
      - "DB_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SIDECAR_NEWSUPDATER=1"
      - "NC_NEWSUPDATER_THREADS=10"
      - "NC_NEWSUPDATER_TIMEOUT=300"
      - "NC_NEWSUPDATER_INTERVAL=900"
      - "NC_NEWSUPDATER_LOGLEVEL=error"
    restart: unless-stopped
    networks:
      - mysql
      - traefik

networks:
  default:
    driver: bridge
    name: nextcloud
  mysql:
    external:
      name: mysql
  traefik:
    external:
      name: traefik
