version: "3.5"

services:
  mariadb:
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    build: ./${MODULE_NAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${DATA_PATH}/mariadb:/config"
    networks:
      - mariadb

  mariadb_adminer:
    image: adminer
    container_name: ${CONTAINER_PREFIX}mariadb_adminer
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb_adminer.entrypoints=https"
      - "traefik.http.routers.mariadb_adminer.rule=Host(`${MARIADB_ADMINER_DOMAIN}`)"
      - "traefik.http.routers.mariadb_adminer.tls=true"
      - "traefik.http.services.mariadb_adminer.loadbalancer.server.port=8080"
    networks:
      - mariadb
      - traefik

networks:
  mariadb:
    driver: bridge
    name: mariadb
  traefik:
    name: traefik
    external: true
