version: "3.5"

services:
  samba_fs:
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    build:
      context: ./${MODULE_NAME}
      args:
        - CHINESE_SPEEDUP
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    restart: unless-stopped
    hostname: ${SAMBA_FS_HOSTNAME}
    cap_add:
      - CAP_NET_ADMIN
    env_file:
      - .env
    volumes:
      # - "${LEGO_CERTS_PATH}:/certs:ro"
      - "${USERDATA_PATH}:/${USERDATA_NAME}"
    # ports:
    #   - 445:445

networks:
  default:
    name: ${VLAN_INTERFACE}
    external: true
