version: "3.5"

services:
  bind:
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    build: 
      context: ./${MODULE_NAME}
      args:
        - CHINESE_SPEEDUP
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    dns_search: ${BASE_DOMAIN}
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
