version: "3.5"

services:
  mysql:
    container_name: ${CONTAINER_PREFIX}redis
    image: redis:6.2.1-alpine
    restart: unless-stopped
    env_file:
      - .env
networks:
  default:
    driver: bridge
    name: redis
