version: "3.5"

services:
  lego:
    build: ./lego
    container_name: ${CONTAINER_PREFIX}lego
    image: ${IMAGE_PREFIX}lego:latest
    restart: unless-stopped
    volumes:
      - "${LEGO_DATA_PATH}:/certs"
    env_file:
      - .env

networks:
  default:
    driver: bridge
    name: lego
