version: "3.5"

services:
  traefik:
    image: "traefik:v2.5.1"
    container_name: ${CONTAINER_PREFIX}traefik
    command:
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --api.dashboard=true
      - --providers.file.filename=/cert.yml
    restart: unless-stopped
    environment:
      - LEGO_CERT_PATH
    ports:
      - "${TREAFIK_BASE_PORT}:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${LEGO_CERTS_PATH}:/certs:ro"
      - "./cert.yml:/cert.yml:ro"
    labels:
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.rule=Host(`traefik.${BASE_URL}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${BASICAUTH_HTPASSWD}"
      - "traefik.http.routers.api.tls=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

networks:
  default:
    driver: bridge
    name: traefik
