#!/usr/bin/with-contenv bash

ip=$(ip addr show | grep -E '^\s*inet' | grep -m1 global | awk '{ print $2 }' | sed 's|/.*||')
export HOST_IP="${HOST_IP:-$ip}"

echo "export exec_user=\"abc\"" > /usr/local/bin/envs.sh
chmod +x /usr/local/bin/envs.sh
source /usr/local/bin/envs.sh

mount_sshfs() { # $1 from location, $2 to location
  if [ ! -d "$2" ]; then
    echo "Create $2"
    mkdir -p $2
  fi
  chown $exec_user:$exec_user $2
  while : 
  do
    echo "Mounting $2 to $1"
    sshfs \
      -o nonempty \
      -o reconnect \
      -o ServerAliveInterval=15 \
      -o ServerAliveCountMax=3 \
      -o UserKnownHostsFile=/dev/null \
      -o StrictHostKeyChecking=no \
      -o allow_other \
      -o auto_unmount \
      -o uid="$PUID" \
      -o gid="$PGID" \
      -o port=22000 \
      root@127.0.0.1:$1 $2 2>&1
    result=$?
    if [ $result == 0 ]; then
      return
    fi
    echo "sshfs mount failed $result"
    sleep 2
  done
}

waiting_file() { # $1 file location
  while :
  do
    if [ -f $1 ]; then
      return
    fi
    echo "Waiting file..."
    sleep 2
  done
}

waiting_ssh() {
  while :
  do
    port_open=$(nc -zv 127.0.0.1 22000 2>&1)
    if [[ "$port_open" == *" succeeded"* ]]; then
      echo "Remote sshfs is ready!"
      return
    fi
    echo "Waiting ssh online..."
    sleep 2
  done
}
if [ "$BIND_DEBUG" == "true" ]; then
  export DLZ_DEBUG="-d 5"
fi

envsubst < /etc/bind/named.conf.j3 > /etc/bind/named.conf

chmod 640 /root
chmod 700 /root/.ssh/
chmod 600 /root/.ssh/id_rsa
mkdir -p /run/named/
chown root:$exec_user /run/named/
chown root:$exec_user /etc/bind/named.conf
# chown root:$exec_user /etc/bind/rndc.conf
chown $exec_user:$exec_user /etc/bind/rndc.key
chmod 644 /etc/bind/rndc.key

if [[ "$ALL_MODS_NAME" == *"samba_dc"* ]]; then
  waiting_ssh
  # sleep 3
  for file in /var/lib/samba/; do
    mount_sshfs $file $file
  done
  mount_sshfs "/etc" /tmp/etc

  chown -R $exec_user:$exec_user /var/bind/
  chmod -R 744 /var/bind/

  # bind.keys
  chown $exec_user:$exec_user /etc/bind/bind.keys
  chmod 600 /etc/bind/bind.keys

  # krb5.conf
  waiting_file "/tmp/etc/krb5.conf"
  cp --remove-destination /tmp/etc/krb5.conf /etc/krb5.conf
  chown $exec_user:$exec_user /etc/krb5.conf
  chmod 644 /etc/krb5.conf

  # run
  chown $exec_user:$exec_user /var/run/named/

  # ln
  rm -rf /etc/samba
  cp -R /tmp/etc/samba /etc/

  # bind-dns
  chown $exec_user:$exec_user /var/lib/samba/bind-dns/
  chmod 770 /var/lib/samba/bind-dns/

  chown $exec_user:$exec_user /var/lib/samba/bind-dns/named.conf
  # dns.keytab
  chmod 640 /var/lib/samba/private/dns.keytab
  chown $exec_user:$exec_user /var/lib/samba/private/dns.keytab
fi

# exec samba-tool dns zonecreate whls 199.168.192.in-addr.arpa -U admin
