version: "3.5"

services:
  lam:
    build: ./lam
    image: ${IMAGE_PREFIX}lam:latest
    container_name: ${CONTAINER_PREFIX}lam
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lam.entrypoints=https"
      - "traefik.http.routers.lam.rule=Host(`${LAM_DOMAIN}`)"
      - "traefik.http.routers.lam.tls=true"
      - "traefik.http.services.lam.loadbalancer.server.port=80"
    environment:
      - "LAM_SKIP_PRECONFIGURE=true"
      - "DEBUG=true"
    env_file:
      - .env
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
