version: "3.5"

services:
  lam:
    image: ldapaccountmanager/lam:7.5
    container_name: ${CONTAINER_PREFIX}lam
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lam.entrypoints=https"
      - "traefik.http.routers.lam.rule=Host(`${LAM_DOMAIN}`)"
      - "traefik.http.routers.lam.tls=true"
      - "traefik.http.services.lam.loadbalancer.server.port=80"
    environment:
      - "LAM_SKIP_PRECONFIGURE=false"
      - "LDAP_SERVER=${SAMBA_SERVER_URL}"
      - "LDAP_DOMAIN=${SAMBA_DOMAIN}"
      - "LDAP_BASE_DN=${SAMBA_BASE_DN}"
      - "LDAP_USER=${SAMBA_ADMIN_DN}"
      - "LDAP_ADMIN_PASSWORD=${SAMBA_ADMIN_PASSWORD}"
      - "LAM_PASSWORD=${LAM_ADMIN_PASSWORD}"
      - "DEBUG=true"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
