version: "3.5"

services:
  samba_dc:
    container_name: ${CONTAINER_PREFIX}${MODULE_NAME}
    build: 
      context: ./${MODULE_NAME}
      args:
        - CHINESE_SPEEDUP
    image: ${IMAGE_PREFIX}${MODULE_NAME}:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - "${LEGO_CERTS_PATH}:/certs:ro"
      - "${DATA_PATH}/samba_dc/var:/var/lib/samba"
